# Generated by Django 2.2.6 on 2020-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.CharField(max_length=100)),
                ('med', models.CharField(max_length=100)),
            ],
        ),
    ]
