# Generated by Django 2.2.6 on 2020-02-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='code',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
