# Generated by Django 2.2.6 on 2020-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200302_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
