# Generated by Django 2.2.6 on 2020-03-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20200302_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
