# Generated by Django 2.2.6 on 2020-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20200302_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
